title: EikoGloria Blog
author: EikoGloria
email: jessicagloria.11a@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website is beeing created for academic purposes. As long as the time pass i'll change this description.

# social links
twitter_username: your-twitter-handle
github_username:  jessicagloria

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
